---
topnav_title: LivePerson Knowledge Center
site_title: LivePerson Knowledge Center
company_name: LivePerson
timezone: America/New_York
disqus_shortname:
host: 127.0.0.1
port: "4000"
google_analytics: UA-132314885-1
extlinks:
  attributes:
    target: _blank
    onclick: linkclick(event, this)
plugins:
- jekyll-last-modified-at
algolia:
  application_id: 51CECYVH5R
  index_name: knowledge_BASE
  settings: false
github:
- metadata
exclude:
- vendor/bundle
- ".idea/"
- ".gitignore"
- node_modules
- gulpfile.js
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
  smart_quotes:
  - apos
  - apos
  - quot
  - quot
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
    comments: true
    search: true
- scope:
    path: ''
    type: 'release'
  values:
    layout: page
- scope:
    path: ''
    type: 'new'
  values:
    layout: page
description: The LivePerson Knowledge Center is the main repository for product knowledge
  and support articles.
url: https://knowledge.liveperson.com
Copyright: https://www.liveperson.com/policies/copyright
Disclaimer: https://www.liveperson.com/policies/disclaimer
TermsofUse: https://www.liveperson.com/policies/terms-of-use
APITermsofUse: https://www.liveperson.com/policies/apitou
PrivacyPolicy: https://www.liveperson.com/policies/privacy
collections:
  release:
    output: true
  new:
    output: true
